// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackNGo.Data;

#nullable disable

namespace TrackNGo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629052629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackNGo.Models.AuditTrailEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditTrailEntries");
                });

            modelBuilder.Entity("TrackNGo.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HeadUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.HasIndex("HeadUserId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentCode = "OM",
                            DepartmentName = "Office of the Mayor"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentCode = "CHO",
                            DepartmentName = "City Health Office"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentCode = "CEO",
                            DepartmentName = "City Engineering Office"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentCode = "HRMO",
                            DepartmentName = "Human Resources (HRMO)"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentCode = "CCR",
                            DepartmentName = "City Civil Registrar"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentCode = "CBO",
                            DepartmentName = "City Budget Office"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentCode = "CAO",
                            DepartmentName = "City Accounting Office"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentCode = "CLO",
                            DepartmentName = "City Legal Office"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentCode = "CSWDO",
                            DepartmentName = "City Social Welfare & Development"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentCode = "CDRRMO",
                            DepartmentName = "City Disaster Risk Reduction & Management"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentCode = "CTO",
                            DepartmentName = "City Tourism Office"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentCode = "CPDO",
                            DepartmentName = "City Planning & Development"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentCode = "AD",
                            DepartmentName = "Admin Division"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentCode = "CASSO",
                            DepartmentName = "City Assessor's Office"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentCode = "CTRO",
                            DepartmentName = "City Treasurer's Office"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentCode = "CAGRO",
                            DepartmentName = "City Agriculture Office"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentCode = "CENRO",
                            DepartmentName = "City Environment & Natural Resources"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentCode = "CGS",
                            DepartmentName = "City General Services"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentCode = "CVO",
                            DepartmentName = "City Veterinary Office"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentCode = "EXT",
                            DepartmentName = "External Client"
                        });
                });

            modelBuilder.Entity("TrackNGo.Models.DigitalSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SignatureImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SignedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SignedByUserId");

                    b.ToTable("DigitalSignatures");
                });

            modelBuilder.Entity("TrackNGo.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ARTAProcessingDays")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentOfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFiled")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EscalationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginatingDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QRCodePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("DateFiled");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentAttachments");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemarkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentComments");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryFlags")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConferenceName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentMetadatas");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentTypeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypeConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General application form",
                            TotalSteps = 5,
                            TypeName = "Application"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Permit requests requiring multiple approvals",
                            TotalSteps = 6,
                            TypeName = "Permit"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Official correspondence",
                            TotalSteps = 4,
                            TypeName = "Letter"
                        },
                        new
                        {
                            Id = 4,
                            Description = "General request documents",
                            TotalSteps = 5,
                            TypeName = "Request"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Financial documents requiring budget review",
                            TotalSteps = 7,
                            TypeName = "Financial Paper"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Internal memo documents",
                            TotalSteps = 4,
                            TypeName = "Memorandum"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Official reports",
                            TotalSteps = 4,
                            TypeName = "Report"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Executive orders from the Mayor",
                            TotalSteps = 5,
                            TypeName = "Executive Order"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Endorsement letters",
                            TotalSteps = 4,
                            TypeName = "Endorsement"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Special orders",
                            TotalSteps = 5,
                            TypeName = "Special Order"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Administrative orders",
                            TotalSteps = 5,
                            TypeName = "Administrative Order"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Certificate issuance requests",
                            TotalSteps = 4,
                            TypeName = "Certificate Request"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Research incentive documents with metadata",
                            TotalSteps = 6,
                            TypeName = "Research Incentive"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Travel order approvals",
                            TotalSteps = 5,
                            TypeName = "Travel Order"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Employee leave applications",
                            TotalSteps = 4,
                            TypeName = "Leave Application"
                        });
                });

            modelBuilder.Entity("TrackNGo.Models.EscalationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ARTAPeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("ARTAThreshold")
                        .HasColumnType("int");

                    b.Property<int>("ActualElapsedDays")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EscalatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<int?>("NotifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ViolatingOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("NotifiedUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("EscalationLogs");
                });

            modelBuilder.Entity("TrackNGo.Models.ExportAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExportScope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExportAuditLogs");
                });

            modelBuilder.Entity("TrackNGo.Models.QRCodeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCodeImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrackingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("QRCodeRecords");
                });

            modelBuilder.Entity("TrackNGo.Models.ReportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("ReportLogs");
                });

            modelBuilder.Entity("TrackNGo.Models.RoutingSlip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionInstruction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("NotedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SlipStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("NotedByUserId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("TargetDepartmentId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("RoutingSlips");
                });

            modelBuilder.Entity("TrackNGo.Models.SMSNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("SMSNotifications");
                });

            modelBuilder.Entity("TrackNGo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExportPasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Office of the Mayor",
                            DepartmentId = 1,
                            Email = "admin@trackngo.mati.gov.ph",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Office of the Mayor",
                            DepartmentId = 1,
                            Email = "mayor@trackngo.mati.gov.ph",
                            FullName = "Hon. City Mayor",
                            IsActive = true,
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 1,
                            Username = "mayor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Office of the Mayor",
                            DepartmentId = 1,
                            Email = "records@trackngo.mati.gov.ph",
                            FullName = "Records Officer",
                            IsActive = true,
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 3,
                            Username = "records"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Office of the Mayor",
                            DepartmentId = 1,
                            Email = "oversight@trackngo.mati.gov.ph",
                            FullName = "CART Oversight Officer",
                            IsActive = true,
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 4,
                            Username = "oversight"
                        });
                });

            modelBuilder.Entity("TrackNGo.Models.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedActions")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AssignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDepartmentId");

                    b.HasIndex("TypeId");

                    b.ToTable("WorkflowSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedActions = "Forward",
                            AssignedDepartmentId = 1,
                            StepName = "Document Received by Clerk",
                            StepNumber = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AllowedActions = "Forward, Return",
                            AssignedDepartmentId = 1,
                            StepName = "Endorsed by Executive Admin",
                            StepNumber = 2,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            AllowedActions = "Forward, Return",
                            StepName = "Reviewed by Department",
                            StepNumber = 3,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            AllowedActions = "Approve, Return, Reject",
                            AssignedDepartmentId = 1,
                            StepName = "Approved by Mayor",
                            StepNumber = 4,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            AllowedActions = "Complete",
                            AssignedDepartmentId = 1,
                            StepName = "Released to Client",
                            StepNumber = 5,
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("TrackNGo.Models.WorkflowTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FromOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("ToOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("WorkflowTransitions");
                });

            modelBuilder.Entity("TrackNGo.Models.AuditTrailEntry", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany("AuditTrail")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGo.Models.Department", b =>
                {
                    b.HasOne("TrackNGo.Models.User", "HeadUser")
                        .WithMany()
                        .HasForeignKey("HeadUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadUser");
                });

            modelBuilder.Entity("TrackNGo.Models.DigitalSignature", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany("Signatures")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.User", "SignedBy")
                        .WithMany()
                        .HasForeignKey("SignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("SignedBy");
                });

            modelBuilder.Entity("TrackNGo.Models.Document", b =>
                {
                    b.HasOne("TrackNGo.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.Department", "DepartmentEntity")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGo.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGo.Models.DocumentTypeConfig", "DocumentTypeConfig")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("DepartmentEntity");

                    b.Navigation("DocumentTypeConfig");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentAttachment", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentComment", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany("Comments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentMetadata", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithOne("Metadata")
                        .HasForeignKey("TrackNGo.Models.DocumentMetadata", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TrackNGo.Models.EscalationLog", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.User", "NotifiedUser")
                        .WithMany()
                        .HasForeignKey("NotifiedUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TrackNGo.Models.User", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Document");

                    b.Navigation("NotifiedUser");

                    b.Navigation("ResolvedBy");
                });

            modelBuilder.Entity("TrackNGo.Models.ExportAuditLog", b =>
                {
                    b.HasOne("TrackNGo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGo.Models.QRCodeRecord", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TrackNGo.Models.ReportLog", b =>
                {
                    b.HasOne("TrackNGo.Models.User", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedBy");
                });

            modelBuilder.Entity("TrackNGo.Models.RoutingSlip", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithOne("RoutingSlip")
                        .HasForeignKey("TrackNGo.Models.RoutingSlip", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.User", "NotedBy")
                        .WithMany()
                        .HasForeignKey("NotedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGo.Models.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("NotedBy");

                    b.Navigation("ReceivedBy");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("TrackNGo.Models.SMSNotification", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany("Notifications")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("TrackNGo.Models.User", b =>
                {
                    b.HasOne("TrackNGo.Models.Department", "DepartmentEntity")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DepartmentEntity");
                });

            modelBuilder.Entity("TrackNGo.Models.WorkflowStep", b =>
                {
                    b.HasOne("TrackNGo.Models.Department", "AssignedDepartment")
                        .WithMany()
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGo.Models.DocumentTypeConfig", "DocumentType")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepartment");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("TrackNGo.Models.WorkflowTransition", b =>
                {
                    b.HasOne("TrackNGo.Models.Document", "Document")
                        .WithMany("Transitions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGo.Models.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("TrackNGo.Models.Document", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditTrail");

                    b.Navigation("Comments");

                    b.Navigation("Metadata");

                    b.Navigation("Notifications");

                    b.Navigation("RoutingSlip");

                    b.Navigation("Signatures");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("TrackNGo.Models.DocumentTypeConfig", b =>
                {
                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
