using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrackNGo.Models
{
    /// <summary>
    /// Report Log entity (Table 15).
    /// Records each report generated by the Compliance Officer.
    /// </summary>
    public class ReportLog
    {
        [Key]
        public int Id { get; set; }

        public int GeneratedByUserId { get; set; }
        [ForeignKey("GeneratedByUserId")]
        public User? GeneratedBy { get; set; }

        /// <summary>Type: Document Summary, Department Performance, Workflow Report.</summary>
        [Required, MaxLength(50)]
        public string ReportType { get; set; } = string.Empty;

        public DateTime DateFrom { get; set; }

        public DateTime DateTo { get; set; }

        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    }
}
